function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // MenuGen
	global.__objectDepths[1] = -2; // CampChar
	global.__objectDepths[2] = 0; // NightCactus
	global.__objectDepths[3] = 0; // Campfire
	global.__objectDepths[4] = 0; // SkeletonChair
	global.__objectDepths[5] = -11; // Menu
	global.__objectDepths[6] = -12; // OptionSelect2
	global.__objectDepths[7] = -12; // OptionSelect
	global.__objectDepths[8] = -12; // CreditsSelect
	global.__objectDepths[9] = -12; // UpdateSelect
	global.__objectDepths[10] = -12; // StatsSelect
	global.__objectDepths[11] = -12; // QuitSelect
	global.__objectDepths[12] = 0; // option
	global.__objectDepths[13] = 0; // option2
	global.__objectDepths[14] = -11; // MusVolSlider
	global.__objectDepths[15] = -11; // SfxVolSlider
	global.__objectDepths[16] = -11; // AmbVolSlider
	global.__objectDepths[17] = -11; // CursorUpDown
	global.__objectDepths[18] = -11; // BloomUpDown
	global.__objectDepths[19] = -11; // GamePadToggle
	global.__objectDepths[20] = -11; // KeyUp
	global.__objectDepths[21] = -11; // KeyDown
	global.__objectDepths[22] = -11; // KeyLeft
	global.__objectDepths[23] = -11; // KeyRight
	global.__objectDepths[24] = -11; // KeySwap
	global.__objectDepths[25] = -11; // KeyPickup
	global.__objectDepths[26] = -12; // KeyReset
	global.__objectDepths[27] = -11; // MouseCPToggle
	global.__objectDepths[28] = -11; // FullScreenToggle
	global.__objectDepths[29] = -11; // BossIntroToggle
	global.__objectDepths[30] = -11; // TimerToggle
	global.__objectDepths[31] = -11; // CameraFollowToggle
	global.__objectDepths[32] = -11; // HighQualityToggle
	global.__objectDepths[33] = -11; // ShakeUpDown
	global.__objectDepths[34] = -11; // FreezeFrameUpDown
	global.__objectDepths[35] = -11; // LoadingScreenSpeedUpDown
	global.__objectDepths[36] = -12; // GameModeUpDown
	global.__objectDepths[37] = -12; // StartingWeaponUpDown
	global.__objectDepths[38] = -12; // DiscAmountUpDown
	global.__objectDepths[39] = -12; // DiscDamageUpDown
	global.__objectDepths[40] = 0; // Back
	global.__objectDepths[41] = 0; // CrownSelect
	global.__objectDepths[42] = 0; // MenuCrown
	global.__objectDepths[43] = -102; // CrownIcon
	global.__objectDepths[44] = 0; // MenuGo
	global.__objectDepths[45] = -99; // Vlambeer
	global.__objectDepths[46] = -12; // CharSelect
	global.__objectDepths[47] = -102; // SkillIcon
	global.__objectDepths[48] = -102; // UltraIcon
	global.__objectDepths[49] = -22; // UnlockPopup
	global.__objectDepths[50] = -12; // LoadoutSelect
	global.__objectDepths[51] = 0; // MakeGame
	global.__objectDepths[52] = -1000; // KeyCont
	global.__objectDepths[53] = -20; // UberCont
	global.__objectDepths[54] = 5; // BackCont
	global.__objectDepths[55] = -100; // LevCont
	global.__objectDepths[56] = 0; // MusCont
	global.__objectDepths[57] = -10; // TopCont
	global.__objectDepths[58] = -100; // GenCont
	global.__objectDepths[59] = -100; // NOWALLSHEREPLEASE
	global.__objectDepths[60] = 10; // Floor
	global.__objectDepths[61] = 0; // FloorMaker
	global.__objectDepths[62] = 10; // FloorLava
	global.__objectDepths[63] = -9; // Top
	global.__objectDepths[64] = -9; // TopSmall
	global.__objectDepths[65] = 9; // FloorExplo
	global.__objectDepths[66] = 0; // Wall
	global.__objectDepths[67] = 100; // Cursor
	global.__objectDepths[68] = -2; // Player
	global.__objectDepths[69] = 0; // ShopSelector
	global.__objectDepths[70] = -12; // ShopWepMod
	global.__objectDepths[71] = -12; // ShopEliteWepChest
	global.__objectDepths[72] = -12; // ShopBigGoldChest
	global.__objectDepths[73] = -12; // ShopWepChest
	global.__objectDepths[74] = -12; // ShopBigWepChest
	global.__objectDepths[75] = -12; // ShopHP
	global.__objectDepths[76] = -12; // ShopAmmoChest
	global.__objectDepths[77] = -12; // ShopAmmo
	global.__objectDepths[78] = -13; // UltraShopMenuArmour
	global.__objectDepths[79] = -13; // UltraShopMenuBigHPChest
	global.__objectDepths[80] = -13; // UltraShopMenuMediumWepChest
	global.__objectDepths[81] = -13; // UltraShopMenuMediumAmmoChest
	global.__objectDepths[82] = -13; // UltraShopMenuDamage
	global.__objectDepths[83] = -13; // UltraShopMenuInvulnerability
	global.__objectDepths[84] = -13; // UltraShopMenuInverted
	global.__objectDepths[85] = -12; // TemporaryBuff
	global.__objectDepths[86] = -13; // UltraShopMenuBuff
	global.__objectDepths[87] = -11; // ShopWheel
	global.__objectDepths[88] = 0; // FrogEgg
	global.__objectDepths[89] = -2; // AllyExploder
	global.__objectDepths[90] = -12; // Feather
	global.__objectDepths[91] = -12; // RavenFeather
	global.__objectDepths[92] = -12; // YungCuzCap
	global.__objectDepths[93] = 4; // Tangle
	global.__objectDepths[94] = 0; // TangleSeed
	global.__objectDepths[95] = 0; // PopoSeed
	global.__objectDepths[96] = 0; // HorrorBeam
	global.__objectDepths[97] = 0; // HorrorBullet
	global.__objectDepths[98] = 0; // PortalStrike
	global.__objectDepths[99] = 0; // SlowFieldEnd
	global.__objectDepths[100] = -3; // PopoSlowFieldFill
	global.__objectDepths[101] = 4; // PopoTangle
	global.__objectDepths[102] = -5; // RogueExplosion
	global.__objectDepths[103] = 0; // Marker
	global.__objectDepths[104] = -1; // FishBoost
	global.__objectDepths[105] = -2; // Ally
	global.__objectDepths[106] = -1; // Infect
	global.__objectDepths[107] = -2; // Partner
	global.__objectDepths[108] = -2; // Sapling
	global.__objectDepths[109] = -2; // AllyFreak
	global.__objectDepths[110] = -9; // CrystalShield
	global.__objectDepths[111] = 0; // GunWarrant
	global.__objectDepths[112] = 0; // EuphoriaShield
	global.__objectDepths[113] = 0; // Rage
	global.__objectDepths[114] = 0; // SheepStorm
	global.__objectDepths[115] = 0; // Notice
	global.__objectDepths[116] = 0; // SleepFX
	global.__objectDepths[117] = -2; // MeltGhost
	global.__objectDepths[118] = -4; // RobotEat
	global.__objectDepths[119] = -4; // SharpTeeth
	global.__objectDepths[120] = 0; // MeltDead
	global.__objectDepths[121] = 0; // Decoy
	global.__objectDepths[122] = 0; // YungCuzDupe
	global.__objectDepths[123] = 0; // ThrowWep
	global.__objectDepths[124] = 0; // AtomPulse
	global.__objectDepths[125] = 0; // Teleport
	global.__objectDepths[126] = 0; // PlantThronebutt
	global.__objectDepths[127] = -3; // UpgradeFX
	global.__objectDepths[128] = 0; // AngelDeflect
	global.__objectDepths[129] = 0; // ArmourStrikeOLD
	global.__objectDepths[130] = -2; // ArmourStrikeHit
	global.__objectDepths[131] = -2; // ArmourStrikeStart
	global.__objectDepths[132] = 0; // ArmourStrike
	global.__objectDepths[133] = 0; // ElementorWallDeflect
	global.__objectDepths[134] = 0; // VikingWall
	global.__objectDepths[135] = 0; // PlayerSpawn
	global.__objectDepths[136] = -2; // RobotTurret
	global.__objectDepths[137] = 0; // AmmoChestMystery
	global.__objectDepths[138] = -2; // HealFX
	global.__objectDepths[139] = 0; // HPPickup
	global.__objectDepths[140] = 0; // AmmoPickup
	global.__objectDepths[141] = 0; // RoguePickup
	global.__objectDepths[142] = 0; // AmmoChest
	global.__objectDepths[143] = 0; // RogueAmmoChest
	global.__objectDepths[144] = 0; // chestprop
	global.__objectDepths[145] = 0; // WeaponChest
	global.__objectDepths[146] = 0; // RadChest
	global.__objectDepths[147] = 0; // HealthChest
	global.__objectDepths[148] = 1; // ChestOpen
	global.__objectDepths[149] = -1; // FXChestOpen
	global.__objectDepths[150] = 0; // BigWeaponChest
	global.__objectDepths[151] = 0; // EliteWeaponChest
	global.__objectDepths[152] = 0; // GiantGoldenWeaponChest
	global.__objectDepths[153] = 1; // Rad
	global.__objectDepths[154] = 0; // WepPickup
	global.__objectDepths[155] = 1; // BigRad
	global.__objectDepths[156] = 0; // GoldChest
	global.__objectDepths[157] = 0; // ProtoChest
	global.__objectDepths[158] = 0; // SlashShotgunPrep
	global.__objectDepths[159] = 0; // SlashDirectorShotgunPrep
	global.__objectDepths[160] = 0; // SlashEraserPrep
	global.__objectDepths[161] = 0; // SlashShotgunBurst
	global.__objectDepths[162] = 0; // SlashDirectorShotgunBurst
	global.__objectDepths[163] = 0; // SlashEraserBurst
	global.__objectDepths[164] = 0; // Burst
	global.__objectDepths[165] = 0; // FrostBurst
	global.__objectDepths[166] = 0; // RogueRifleBurst
	global.__objectDepths[167] = 0; // SwarmBurst
	global.__objectDepths[168] = 0; // RocketGloveBurst
	global.__objectDepths[169] = 0; // SmallGrenadeBurst
	global.__objectDepths[170] = 0; // DoomBurst
	global.__objectDepths[171] = 0; // NukeBurst
	global.__objectDepths[172] = 0; // SeekerShotgunBurst
	global.__objectDepths[173] = 0; // SeekerCannonBurst
	global.__objectDepths[174] = 0; // LaserWaveBurst
	global.__objectDepths[175] = 0; // MissileBurst
	global.__objectDepths[176] = 0; // DirectorBurst
	global.__objectDepths[177] = 0; // SlugBurst
	global.__objectDepths[178] = 0; // ShotgunBurst
	global.__objectDepths[179] = 0; // PistoleBurst
	global.__objectDepths[180] = 0; // BeamShotgunBurst
	global.__objectDepths[181] = 0; // EnergyJackhammerBurst
	global.__objectDepths[182] = 0; // SawBurst
	global.__objectDepths[183] = 0; // FlameBurst
	global.__objectDepths[184] = 0; // SnowBurst
	global.__objectDepths[185] = 0; // SnowDragonBurst
	global.__objectDepths[186] = 0; // TimeThrowerBurst
	global.__objectDepths[187] = 0; // ToxicSound
	global.__objectDepths[188] = 0; // ToxicBurst
	global.__objectDepths[189] = 0; // ToxicDragonBurst
	global.__objectDepths[190] = 0; // ToxicDragonSound
	global.__objectDepths[191] = 0; // DragonBurst
	global.__objectDepths[192] = 0; // DragonSound
	global.__objectDepths[193] = 0; // FlameSound
	global.__objectDepths[194] = 0; // SnowSound
	global.__objectDepths[195] = 0; // SnowDragonSound
	global.__objectDepths[196] = 0; // HeavyBurst
	global.__objectDepths[197] = 0; // BouncerBurst
	global.__objectDepths[198] = 0; // EraserBurst
	global.__objectDepths[199] = 0; // DirectorEraserBurst
	global.__objectDepths[200] = 0; // FlameDirectorEraserBurst
	global.__objectDepths[201] = 0; // EraserBurst2
	global.__objectDepths[202] = 0; // Burst2
	global.__objectDepths[203] = 0; // UltraFlameBurst
	global.__objectDepths[204] = 0; // FlameEraserBurst
	global.__objectDepths[205] = 0; // WaveBurst
	global.__objectDepths[206] = 0; // UltraWaveBurst
	global.__objectDepths[207] = 0; // EnemyWaveBurst
	global.__objectDepths[208] = 0; // EnemyEraserBurst
	global.__objectDepths[209] = 0; // FlameWaveBurst
	global.__objectDepths[210] = -100; // IonBurst
	global.__objectDepths[211] = -100; // KrakenIonBurst
	global.__objectDepths[212] = -100; // ToxicIonBurst
	global.__objectDepths[213] = -100; // SuperIonBurst
	global.__objectDepths[214] = 0; // ChargeShotgun
	global.__objectDepths[215] = 0; // ChargeSplinterGun
	global.__objectDepths[216] = 0; // ChargeFlakCannon
	global.__objectDepths[217] = 0; // ChargeLaser
	global.__objectDepths[218] = 0; // WeaponCharge
	global.__objectDepths[219] = 0; // HumphryProjectile
	global.__objectDepths[220] = 0; // projectile
	global.__objectDepths[221] = -5; // MeatExplosion
	global.__objectDepths[222] = 1; // Shell
	global.__objectDepths[223] = -2; // EnemyBullet1
	global.__objectDepths[224] = -2; // EnemyBullet2
	global.__objectDepths[225] = -2; // LightningHit
	global.__objectDepths[226] = -2; // LightningSpawn
	global.__objectDepths[227] = 0; // Lightning
	global.__objectDepths[228] = 0; // Tentacle
	global.__objectDepths[229] = 0; // UltraLightning
	global.__objectDepths[230] = 0; // LaserCannon
	global.__objectDepths[231] = 0; // BloodBullet
	global.__objectDepths[232] = 0; // MiniFlameCannonBall
	global.__objectDepths[233] = 0; // EnemyLightningBall
	global.__objectDepths[234] = 0; // FlameCannonBall
	global.__objectDepths[235] = 0; // BloodCannonBall
	global.__objectDepths[236] = 0; // ToxicCannonBall
	global.__objectDepths[237] = 0; // IceCannonBall
	global.__objectDepths[238] = 0; // HeavyBullet
	global.__objectDepths[239] = 0; // FatBullet
	global.__objectDepths[240] = 0; // FrozenEnemy
	global.__objectDepths[241] = 0; // FrozenPlayer
	global.__objectDepths[242] = 0; // PartnerBullet
	global.__objectDepths[243] = 0; // FreezeBullet
	global.__objectDepths[244] = 0; // Bullet3
	global.__objectDepths[245] = 0; // EnemyBouncerBullet
	global.__objectDepths[246] = -5; // Morph
	global.__objectDepths[247] = -5; // ExplosiveMorph
	global.__objectDepths[248] = 0; // Ray
	global.__objectDepths[249] = 0; // Implosion
	global.__objectDepths[250] = 0; // Slug
	global.__objectDepths[251] = 0; // UltraSlug
	global.__objectDepths[252] = 0; // DirectorSlug
	global.__objectDepths[253] = 0; // HeavySlug
	global.__objectDepths[254] = 0; // EnemyBullet3
	global.__objectDepths[255] = -1; // BulletHit
	global.__objectDepths[256] = 0; // LaserCharge
	global.__objectDepths[257] = 0; // PlasmaBall
	global.__objectDepths[258] = 0; // ElectroBallSpawn
	global.__objectDepths[259] = 0; // ElectroBall
	global.__objectDepths[260] = 0; // PopoPlasmaBall
	global.__objectDepths[261] = 0; // MiniPlasmaBall
	global.__objectDepths[262] = 0; // PlasmaBig
	global.__objectDepths[263] = 0; // PlasmaHuge
	global.__objectDepths[264] = 0; // BloodGrenade
	global.__objectDepths[265] = 0; // PopoNade
	global.__objectDepths[266] = 0; // Grenade
	global.__objectDepths[267] = 0; // SplitGrenade
	global.__objectDepths[268] = 0; // DoomNadeCluster
	global.__objectDepths[269] = 0; // DoomGrenade
	global.__objectDepths[270] = 0; // Termite
	global.__objectDepths[271] = 0; // SmallGrenade
	global.__objectDepths[272] = 0; // Flare
	global.__objectDepths[273] = 0; // FrostFlare
	global.__objectDepths[274] = 0; // TimeReset
	global.__objectDepths[275] = 0; // TimeBomb
	global.__objectDepths[276] = 0; // Rocket
	global.__objectDepths[277] = 0; // FlakBullet
	global.__objectDepths[278] = 0; // FrostFlakBullet
	global.__objectDepths[279] = 0; // UltraFlakBullet
	global.__objectDepths[280] = 0; // SuperFlakBullet
	global.__objectDepths[281] = 0; // SuperBouncerFlakBullet
	global.__objectDepths[282] = 0; // BouncerFlakBullet
	global.__objectDepths[283] = -2; // AllyBullet
	global.__objectDepths[284] = -2; // IDPDBullet
	global.__objectDepths[285] = 0; // EnemyLaser
	global.__objectDepths[286] = 0; // IDPDLaser
	global.__objectDepths[287] = -2; // EnemyBullet4
	global.__objectDepths[288] = -2; // EnemyBullet5
	global.__objectDepths[289] = 0; // JockRocket
	global.__objectDepths[290] = 0; // PopoMissile
	global.__objectDepths[291] = 0; // HyperGrenade
	global.__objectDepths[292] = 0; // HyperSniper
	global.__objectDepths[293] = 0; // HyperLightning
	global.__objectDepths[294] = 0; // LineGrenade
	global.__objectDepths[295] = 0; // HyperInfuseBolt
	global.__objectDepths[296] = 0; // LineToxic
	global.__objectDepths[297] = 0; // LineBlood
	global.__objectDepths[298] = 0; // LineFire
	global.__objectDepths[299] = 0; // EnemyLineFire
	global.__objectDepths[300] = 0; // HyperPlasmaCannon
	global.__objectDepths[301] = 0; // HyperBloodGrenade
	global.__objectDepths[302] = 0; // HyperSlug
	global.__objectDepths[303] = 0; // HyperHeavySlug
	global.__objectDepths[304] = 0; // PopoSlug
	global.__objectDepths[305] = 0; // Bullet1
	global.__objectDepths[306] = 0; // MoneyBullet
	global.__objectDepths[307] = 0; // RogueBullet
	global.__objectDepths[308] = 0; // DisperseBullet
	global.__objectDepths[309] = 0; // DisperseDisperseBullet
	global.__objectDepths[310] = 0; // DisperseRocket
	global.__objectDepths[311] = 0; // DispersePellet
	global.__objectDepths[312] = 0; // DisperseLaser
	global.__objectDepths[313] = 0; // AIBullet
	global.__objectDepths[314] = 0; // Bullet2
	global.__objectDepths[315] = 0; // Potato
	global.__objectDepths[316] = 0; // Bullet6
	global.__objectDepths[317] = 0; // Bullet4
	global.__objectDepths[318] = 0; // Bullet5
	global.__objectDepths[319] = 0; // Bullet8
	global.__objectDepths[320] = 0; // Bullet7
	global.__objectDepths[321] = 0; // Bullet9
	global.__objectDepths[322] = 0; // Nuke
	global.__objectDepths[323] = 0; // SterNuke
	global.__objectDepths[324] = 0; // Laser
	global.__objectDepths[325] = 0; // MegaLaser
	global.__objectDepths[326] = 0; // Splinter
	global.__objectDepths[327] = 0; // UltraSplinter
	global.__objectDepths[328] = 0; // InfuseBolt
	global.__objectDepths[329] = 0; // UltraInfuseBolt
	global.__objectDepths[330] = 0; // SwordBullet
	global.__objectDepths[331] = 0; // ShankBullet
	global.__objectDepths[332] = 0; // EnergySwordBullet
	global.__objectDepths[333] = 0; // EnergyShankBullet
	global.__objectDepths[334] = 1; // BoltTrail
	global.__objectDepths[335] = 0; // GoldenExplosiveBolt
	global.__objectDepths[336] = 0; // ToxicBolt
	global.__objectDepths[337] = 0; // ExplosiveBolt
	global.__objectDepths[338] = 0; // Bolt
	global.__objectDepths[339] = 0; // LightningBolt
	global.__objectDepths[340] = 0; // HeavyBolt
	global.__objectDepths[341] = 0; // UltraBolt
	global.__objectDepths[342] = 0; // SeekerBolt
	global.__objectDepths[343] = 0; // SwarmBolt
	global.__objectDepths[344] = -10; // Missile
	global.__objectDepths[345] = -10; // EnemyMissile
	global.__objectDepths[346] = 0; // UltraSeekerBolt
	global.__objectDepths[347] = 0; // BoltStick
	global.__objectDepths[348] = 0; // GyroBurst
	global.__objectDepths[349] = 0; // Disc
	global.__objectDepths[350] = 0; // PermanentDisc
	global.__objectDepths[351] = 0; // Blade
	global.__objectDepths[352] = 0; // Yoyo
	global.__objectDepths[353] = 0; // SplitBlade
	global.__objectDepths[354] = 0; // SuperSplitBlade
	global.__objectDepths[355] = 0; // UltraBlade
	global.__objectDepths[356] = 0; // EnemyDisc
	global.__objectDepths[357] = 1; // DiscTrail
	global.__objectDepths[358] = 1; // DiscBounce
	global.__objectDepths[359] = 1; // DiscDisappear
	global.__objectDepths[360] = 1; // Deflect
	global.__objectDepths[361] = -2; // Flame
	global.__objectDepths[362] = -2; // IceFlame
	global.__objectDepths[363] = -2; // UltraFlame
	global.__objectDepths[364] = -5; // PlasmaImpact
	global.__objectDepths[365] = -5; // PopoPlasmaImpact
	global.__objectDepths[366] = -5; // MiniPlasmaImpact
	global.__objectDepths[367] = -1; // PlasmaFX
	global.__objectDepths[368] = -5; // IonImpact
	global.__objectDepths[369] = 0; // EnemySlash
	global.__objectDepths[370] = 0; // AssassinSlash
	global.__objectDepths[371] = 0; // PopoSlash
	global.__objectDepths[372] = 0; // EnergySlash
	global.__objectDepths[373] = 0; // GhettoBlast
	global.__objectDepths[374] = 0; // EnergyHammerSlash
	global.__objectDepths[375] = 0; // EnergyShank
	global.__objectDepths[376] = 0; // Shank
	global.__objectDepths[377] = 0; // LightningShank
	global.__objectDepths[378] = 0; // Slash
	global.__objectDepths[379] = 0; // BlackSwordSlash
	global.__objectDepths[380] = 0; // DarkSwordSlash
	global.__objectDepths[381] = 0; // GhostEffect
	global.__objectDepths[382] = 0; // GhostSlash
	global.__objectDepths[383] = 0; // RocketSlash
	global.__objectDepths[384] = 0; // BigSlash
	global.__objectDepths[385] = 0; // FrostSlash
	global.__objectDepths[386] = 0; // BloodSlash
	global.__objectDepths[387] = 0; // LightningSlash
	global.__objectDepths[388] = 0; // KrakenSlash
	global.__objectDepths[389] = 0; // MorphSlash
	global.__objectDepths[390] = -1; // EBulletHit
	global.__objectDepths[391] = -5; // ExplosionNonLethal
	global.__objectDepths[392] = -5; // Explosion
	global.__objectDepths[393] = -5; // ExplosionMask
	global.__objectDepths[394] = -5; // SmallExplosion
	global.__objectDepths[395] = -5; // ExplosionStop
	global.__objectDepths[396] = -5; // WallBreak
	global.__objectDepths[397] = -5; // PopoExplosion
	global.__objectDepths[398] = -1; // MeleeHitWall
	global.__objectDepths[399] = -2; // ToxicThrowerGas
	global.__objectDepths[400] = -2; // ToxicGas
	global.__objectDepths[401] = -2; // TrapFire
	global.__objectDepths[402] = 0; // Mine
	global.__objectDepths[403] = -2; // SentryGun
	global.__objectDepths[404] = 0; // hitme
	global.__objectDepths[405] = 0; // enemy
	global.__objectDepths[406] = 0; // SpikeTrap
	global.__objectDepths[407] = -2; // MaggotSpawn
	global.__objectDepths[408] = -5; // MaggotExplosion
	global.__objectDepths[409] = -5; // MaggotExplosionInverted
	global.__objectDepths[410] = -2; // Maggot
	global.__objectDepths[411] = -2; // MaggotInverted
	global.__objectDepths[412] = 0; // ChesireCatTail
	global.__objectDepths[413] = 0; // You
	global.__objectDepths[414] = 0; // InvertedChesireCatTail
	global.__objectDepths[415] = 0; // WantBoss
	global.__objectDepths[416] = 0; // ChesireCatExplosion
	global.__objectDepths[417] = -2; // ChesireCat
	global.__objectDepths[418] = -2; // InvertedChesireCat
	global.__objectDepths[419] = -2; // BecomeScrapBoss
	global.__objectDepths[420] = -2; // ScrapBoss
	global.__objectDepths[421] = -2; // InvertedScrapBoss
	global.__objectDepths[422] = -2; // BecomeInvertedScrapBoss
	global.__objectDepths[423] = -2; // ScrapBossMissile
	global.__objectDepths[424] = -2; // BanditBoss
	global.__objectDepths[425] = -2; // InvertedBanditBoss
	global.__objectDepths[426] = 1; // ScrapBossCorpse
	global.__objectDepths[427] = 0; // BigDogExplo
	global.__objectDepths[428] = -1; // HotDrakePrepSmoke
	global.__objectDepths[429] = -2; // HotDrake
	global.__objectDepths[430] = -2; // InvertedHotDrake
	global.__objectDepths[431] = 0; // HotDrakeFlameCannon
	global.__objectDepths[432] = 0; // HotDrakeSplitBall
	global.__objectDepths[433] = 0; // InvertedHotDrakeSplitBall
	global.__objectDepths[434] = -2; // LilHunter
	global.__objectDepths[435] = 0; // LilHunterDie
	global.__objectDepths[436] = -2; // LilHunterFly
	global.__objectDepths[437] = 0; // InvertedLilHunterDie
	global.__objectDepths[438] = -2; // InvertedLilHunterFly
	global.__objectDepths[439] = -2; // InvertedLilHunter
	global.__objectDepths[440] = -2; // BigFish
	global.__objectDepths[441] = -3; // BigMachineTurret
	global.__objectDepths[442] = -43; // BigMachineLaser
	global.__objectDepths[443] = 0; // BigMachineMask
	global.__objectDepths[444] = -2; // BigMachine
	global.__objectDepths[445] = -3; // InvertedBigMachineTurret
	global.__objectDepths[446] = -43; // InvertedBigMachineLaser
	global.__objectDepths[447] = -2; // InvertedBigMachine
	global.__objectDepths[448] = -1; // LabTrap
	global.__objectDepths[449] = -2; // AssassinBoss
	global.__objectDepths[450] = -2; // InvertedAssassinBoss
	global.__objectDepths[451] = -2; // FireBaller
	global.__objectDepths[452] = -2; // SuperFireBaller
	global.__objectDepths[453] = -2; // FireBat
	global.__objectDepths[454] = -2; // LavaBallEnemy
	global.__objectDepths[455] = -2; // InvertedLavaBallEnemy
	global.__objectDepths[456] = -2; // InvertedSuperFireBaller
	global.__objectDepths[457] = -2; // InvertedFireBaller
	global.__objectDepths[458] = -2; // InvertedFireBat
	global.__objectDepths[459] = -2; // Necromancer
	global.__objectDepths[460] = -2; // InvertedNecromancer
	global.__objectDepths[461] = -2; // Freak
	global.__objectDepths[462] = -2; // InvertedFreak
	global.__objectDepths[463] = -2; // ExploFreak
	global.__objectDepths[464] = -2; // InvertedExploFreak
	global.__objectDepths[465] = 1; // ReviveFX
	global.__objectDepths[466] = 1; // ReviveArea
	global.__objectDepths[467] = 1; // InvertedReviveArea
	global.__objectDepths[468] = -2; // RhinoFreak
	global.__objectDepths[469] = -2; // InvertedRhinoFreak
	global.__objectDepths[470] = 0; // MutantTube
	global.__objectDepths[471] = 0; // InvertedMutantTube
	global.__objectDepths[472] = -2; // Bandit
	global.__objectDepths[473] = -2; // LaserBandit
	global.__objectDepths[474] = -2; // JungleBandit
	global.__objectDepths[475] = -2; // EraserBandit
	global.__objectDepths[476] = -2; // BanditInverted
	global.__objectDepths[477] = -2; // CardGuy2
	global.__objectDepths[478] = -2; // CardGuy
	global.__objectDepths[479] = -2; // TeaPot
	global.__objectDepths[480] = -2; // TeaPotMissile
	global.__objectDepths[481] = -2; // InvertedCardGuy
	global.__objectDepths[482] = -2; // InvertedCardGuy2
	global.__objectDepths[483] = -2; // InvertedTeaPot
	global.__objectDepths[484] = -2; // TeaPotNuke
	global.__objectDepths[485] = 0; // becomenemy
	global.__objectDepths[486] = -2; // BigMaggotBurrow
	global.__objectDepths[487] = -2; // BigMaggot
	global.__objectDepths[488] = -2; // BigMaggotBurrowInverted
	global.__objectDepths[489] = -2; // BigMaggotInverted
	global.__objectDepths[490] = -2; // Molesarge
	global.__objectDepths[491] = -2; // Molefish
	global.__objectDepths[492] = -2; // Mimic
	global.__objectDepths[493] = -2; // SuperMimic
	global.__objectDepths[494] = -2; // LaserCrystal
	global.__objectDepths[495] = -2; // LightningCrystal
	global.__objectDepths[496] = -2; // Spider
	global.__objectDepths[497] = -2; // InvertedSpider
	global.__objectDepths[498] = 0; // RadMaggotChest
	global.__objectDepths[499] = -5; // RadMaggotExplosion
	global.__objectDepths[500] = -2; // RadMaggot
	global.__objectDepths[501] = -2; // Gator
	global.__objectDepths[502] = 1; // GatorSmoke
	global.__objectDepths[503] = -2; // InvertedGator
	global.__objectDepths[504] = -2; // Exploder
	global.__objectDepths[505] = -2; // InvertedExploder
	global.__objectDepths[506] = -2; // InvertedSuperFrog
	global.__objectDepths[507] = -5; // ExploderExplo
	global.__objectDepths[508] = -2; // SuperFrog
	global.__objectDepths[509] = -2; // Rat
	global.__objectDepths[510] = -2; // InvertedRat
	global.__objectDepths[511] = -2; // FastRat
	global.__objectDepths[512] = -2; // InvertedFastRat
	global.__objectDepths[513] = -2; // Ratking
	global.__objectDepths[514] = -2; // InvertedRatking
	global.__objectDepths[515] = -2; // RatkingRage
	global.__objectDepths[516] = -2; // InvertedRatkingRage
	global.__objectDepths[517] = -2; // Raven
	global.__objectDepths[518] = -2; // Thief
	global.__objectDepths[519] = -2; // RavenFly
	global.__objectDepths[520] = -2; // Salamander
	global.__objectDepths[521] = -2; // InvertedSalamander
	global.__objectDepths[522] = -2; // Sniper
	global.__objectDepths[523] = -2; // InvertedSniper
	global.__objectDepths[524] = -2; // InvertedRaven
	global.__objectDepths[525] = -2; // InvertedRavenFly
	global.__objectDepths[526] = -2; // MeleeBandit
	global.__objectDepths[527] = 1; // MeleeFake
	global.__objectDepths[528] = 1; // InvertedMeleeFake
	global.__objectDepths[529] = -2; // InvertedMeleeBandit
	global.__objectDepths[530] = -2; // Jock
	global.__objectDepths[531] = 0; // SnowMan
	global.__objectDepths[532] = -2; // GoldScorpion
	global.__objectDepths[533] = -2; // Scorpion
	global.__objectDepths[534] = -2; // InvertedScorpion
	global.__objectDepths[535] = -2; // ScorpionBulletHit
	global.__objectDepths[536] = -2; // BoneFish
	global.__objectDepths[537] = -2; // Crab
	global.__objectDepths[538] = -2; // Turtle
	global.__objectDepths[539] = -1; // Trap
	global.__objectDepths[540] = 9; // TrapScorchMark
	global.__objectDepths[541] = -2; // Wolf
	global.__objectDepths[542] = -2; // SnowBot
	global.__objectDepths[543] = -2; // SnowBotCar
	global.__objectDepths[544] = -2; // DiscGuy
	global.__objectDepths[545] = -2; // GoldSnowTank
	global.__objectDepths[546] = -2; // SnowTank
	global.__objectDepths[547] = 0; // SnowTankExplo
	global.__objectDepths[548] = -2; // InvertedSnowTank
	global.__objectDepths[549] = -2; // InvertedDiscGuy
	global.__objectDepths[550] = -2; // InvertedWolf
	global.__objectDepths[551] = -2; // InvertedSnowBot
	global.__objectDepths[552] = -2; // InvertedSnowBotCar
	global.__objectDepths[553] = -2; // Inspector
	global.__objectDepths[554] = -2; // SegwayPopo
	global.__objectDepths[555] = -2; // Shielder
	global.__objectDepths[556] = -1; // IDPDSpawn
	global.__objectDepths[557] = 0; // IDPDPortalCharge
	global.__objectDepths[558] = -2; // Grunt
	global.__objectDepths[559] = -1; // VanSpawn
	global.__objectDepths[560] = -1; // IDPDVan
	global.__objectDepths[561] = -2; // EliteGrunt
	global.__objectDepths[562] = -2; // EliteShielder
	global.__objectDepths[563] = -2; // EliteInspector
	global.__objectDepths[564] = -9; // PopoShield
	global.__objectDepths[565] = -2; // Sheep
	global.__objectDepths[566] = -2; // ExplosiveSheep
	global.__objectDepths[567] = -4; // AcidStreak
	global.__objectDepths[568] = -11; // AutoAimUpDown
	global.__objectDepths[569] = 0; // BECOMETARGET
	global.__objectDepths[570] = 0; // prop
	global.__objectDepths[571] = 0; // Server
	global.__objectDepths[572] = 0; // InvertedServer
	global.__objectDepths[573] = 0; // Terminal
	global.__objectDepths[574] = 0; // InvertedTerminal
	global.__objectDepths[575] = 0; // Barrel
	global.__objectDepths[576] = 0; // Tube
	global.__objectDepths[577] = 0; // InvertedTube
	global.__objectDepths[578] = 0; // StreetLight
	global.__objectDepths[579] = 0; // Torch
	global.__objectDepths[580] = 0; // Tires
	global.__objectDepths[581] = 0; // ToxicBarrel
	global.__objectDepths[582] = 0; // SodaMachine
	global.__objectDepths[583] = 0; // BigFishSkull
	global.__objectDepths[584] = 0; // Anchor
	global.__objectDepths[585] = 0; // WaterMineExplo
	global.__objectDepths[586] = 0; // WaterMine
	global.__objectDepths[587] = 0; // BigSkull
	global.__objectDepths[588] = 0; // Cactus
	global.__objectDepths[589] = 0; // Coral
	global.__objectDepths[590] = 0; // WaterPlant
	global.__objectDepths[591] = 0; // CandyCane
	global.__objectDepths[592] = 0; // Mushroom
	global.__objectDepths[593] = 0; // BigMushroom
	global.__objectDepths[594] = -4; // BloodStreak
	global.__objectDepths[595] = 0; // Bones
	global.__objectDepths[596] = 0; // TopDecal
	global.__objectDepths[597] = -2; // Breath
	global.__objectDepths[598] = 0; // CanSpawnBoss
	global.__objectDepths[599] = 0; // Car
	global.__objectDepths[600] = 0; // CarThrow
	global.__objectDepths[601] = 0; // CarVenus
	global.__objectDepths[602] = 0; // CarVenusFixed
	global.__objectDepths[603] = 1; // CaveSparkle
	global.__objectDepths[604] = 9; // CharredGround
	global.__objectDepths[605] = 0; // Cocoon
	global.__objectDepths[606] = 1; // Corpse
	global.__objectDepths[607] = -1; // Crown
	global.__objectDepths[608] = -2; // CrownGuardian
	global.__objectDepths[609] = 0; // GuardianStatue
	global.__objectDepths[610] = 0; // GuardianDeflect
	global.__objectDepths[611] = 0; // CrownPed
	global.__objectDepths[612] = 0; // WeaponMod
	global.__objectDepths[613] = -1; // CrownPickup
	global.__objectDepths[614] = 0; // Crystal
	global.__objectDepths[615] = -1; // Curse
	global.__objectDepths[616] = -1; // Debris
	global.__objectDepths[617] = -98; // Drama
	global.__objectDepths[618] = -99; // DramaCamera
	global.__objectDepths[619] = -1; // Drip
	global.__objectDepths[620] = -1; // Dust
	global.__objectDepths[621] = 0; // GoldBarrel
	global.__objectDepths[622] = 0; // Hydrant
	global.__objectDepths[623] = 0; // LavaBubble
	global.__objectDepths[624] = -4; // LevelUp
	global.__objectDepths[625] = 0; // LogMenu
	global.__objectDepths[626] = 0; // MoneyPile
	global.__objectDepths[627] = 0; // Pipe
	global.__objectDepths[628] = 0; // PizzaBox
	global.__objectDepths[629] = 8; // PizzaEntrance
	global.__objectDepths[630] = -9; // PopupText
	global.__objectDepths[631] = -8; // Portal
	global.__objectDepths[632] = 0; // PortalShock
	global.__objectDepths[633] = -1; // ProtoStatue
	global.__objectDepths[634] = -10; // RainDrop
	global.__objectDepths[635] = 1; // RainSplash
	global.__objectDepths[636] = 0; // ImpactFX
	global.__objectDepths[637] = 5; // MeltSplat
	global.__objectDepths[638] = 1; // Scorchmark
	global.__objectDepths[639] = 0; // Flames
	global.__objectDepths[640] = 0; // PopoFlames
	global.__objectDepths[641] = 5; // BigScorchMark
	global.__objectDepths[642] = -1; // SmallChestFade
	global.__objectDepths[643] = -1; // SmallChestPickup
	global.__objectDepths[644] = -1; // Smoke
	global.__objectDepths[645] = -10; // SnowFlake
	global.__objectDepths[646] = 0; // Spiral
	global.__objectDepths[647] = -101; // SpiralCont
	global.__objectDepths[648] = -1000; // SpiralDebris
	global.__objectDepths[649] = -1000; // SpiralStar
	global.__objectDepths[650] = -1; // TV
	global.__objectDepths[651] = -4; // WepSwap
	global.__objectDepths[652] = 1; // Wind
	global.__objectDepths[653] = 1; // WindNight
	global.__objectDepths[654] = 0; // YVStatue


	global.__objectNames[0] = "MenuGen";
	global.__objectNames[1] = "CampChar";
	global.__objectNames[2] = "NightCactus";
	global.__objectNames[3] = "Campfire";
	global.__objectNames[4] = "SkeletonChair";
	global.__objectNames[5] = "Menu";
	global.__objectNames[6] = "OptionSelect2";
	global.__objectNames[7] = "OptionSelect";
	global.__objectNames[8] = "CreditsSelect";
	global.__objectNames[9] = "UpdateSelect";
	global.__objectNames[10] = "StatsSelect";
	global.__objectNames[11] = "QuitSelect";
	global.__objectNames[12] = "option";
	global.__objectNames[13] = "option2";
	global.__objectNames[14] = "MusVolSlider";
	global.__objectNames[15] = "SfxVolSlider";
	global.__objectNames[16] = "AmbVolSlider";
	global.__objectNames[17] = "CursorUpDown";
	global.__objectNames[18] = "BloomUpDown";
	global.__objectNames[19] = "GamePadToggle";
	global.__objectNames[20] = "KeyUp";
	global.__objectNames[21] = "KeyDown";
	global.__objectNames[22] = "KeyLeft";
	global.__objectNames[23] = "KeyRight";
	global.__objectNames[24] = "KeySwap";
	global.__objectNames[25] = "KeyPickup";
	global.__objectNames[26] = "KeyReset";
	global.__objectNames[27] = "MouseCPToggle";
	global.__objectNames[28] = "FullScreenToggle";
	global.__objectNames[29] = "BossIntroToggle";
	global.__objectNames[30] = "TimerToggle";
	global.__objectNames[31] = "CameraFollowToggle";
	global.__objectNames[32] = "HighQualityToggle";
	global.__objectNames[33] = "ShakeUpDown";
	global.__objectNames[34] = "FreezeFrameUpDown";
	global.__objectNames[35] = "LoadingScreenSpeedUpDown";
	global.__objectNames[36] = "GameModeUpDown";
	global.__objectNames[37] = "StartingWeaponUpDown";
	global.__objectNames[38] = "DiscAmountUpDown";
	global.__objectNames[39] = "DiscDamageUpDown";
	global.__objectNames[40] = "Back";
	global.__objectNames[41] = "CrownSelect";
	global.__objectNames[42] = "MenuCrown";
	global.__objectNames[43] = "CrownIcon";
	global.__objectNames[44] = "MenuGo";
	global.__objectNames[45] = "Vlambeer";
	global.__objectNames[46] = "CharSelect";
	global.__objectNames[47] = "SkillIcon";
	global.__objectNames[48] = "UltraIcon";
	global.__objectNames[49] = "UnlockPopup";
	global.__objectNames[50] = "LoadoutSelect";
	global.__objectNames[51] = "MakeGame";
	global.__objectNames[52] = "KeyCont";
	global.__objectNames[53] = "UberCont";
	global.__objectNames[54] = "BackCont";
	global.__objectNames[55] = "LevCont";
	global.__objectNames[56] = "MusCont";
	global.__objectNames[57] = "TopCont";
	global.__objectNames[58] = "GenCont";
	global.__objectNames[59] = "NOWALLSHEREPLEASE";
	global.__objectNames[60] = "Floor";
	global.__objectNames[61] = "FloorMaker";
	global.__objectNames[62] = "FloorLava";
	global.__objectNames[63] = "Top";
	global.__objectNames[64] = "TopSmall";
	global.__objectNames[65] = "FloorExplo";
	global.__objectNames[66] = "Wall";
	global.__objectNames[67] = "Cursor";
	global.__objectNames[68] = "Player";
	global.__objectNames[69] = "ShopSelector";
	global.__objectNames[70] = "ShopWepMod";
	global.__objectNames[71] = "ShopEliteWepChest";
	global.__objectNames[72] = "ShopBigGoldChest";
	global.__objectNames[73] = "ShopWepChest";
	global.__objectNames[74] = "ShopBigWepChest";
	global.__objectNames[75] = "ShopHP";
	global.__objectNames[76] = "ShopAmmoChest";
	global.__objectNames[77] = "ShopAmmo";
	global.__objectNames[78] = "UltraShopMenuArmour";
	global.__objectNames[79] = "UltraShopMenuBigHPChest";
	global.__objectNames[80] = "UltraShopMenuMediumWepChest";
	global.__objectNames[81] = "UltraShopMenuMediumAmmoChest";
	global.__objectNames[82] = "UltraShopMenuDamage";
	global.__objectNames[83] = "UltraShopMenuInvulnerability";
	global.__objectNames[84] = "UltraShopMenuInverted";
	global.__objectNames[85] = "TemporaryBuff";
	global.__objectNames[86] = "UltraShopMenuBuff";
	global.__objectNames[87] = "ShopWheel";
	global.__objectNames[88] = "FrogEgg";
	global.__objectNames[89] = "AllyExploder";
	global.__objectNames[90] = "Feather";
	global.__objectNames[91] = "RavenFeather";
	global.__objectNames[92] = "YungCuzCap";
	global.__objectNames[93] = "Tangle";
	global.__objectNames[94] = "TangleSeed";
	global.__objectNames[95] = "PopoSeed";
	global.__objectNames[96] = "HorrorBeam";
	global.__objectNames[97] = "HorrorBullet";
	global.__objectNames[98] = "PortalStrike";
	global.__objectNames[99] = "SlowFieldEnd";
	global.__objectNames[100] = "PopoSlowFieldFill";
	global.__objectNames[101] = "PopoTangle";
	global.__objectNames[102] = "RogueExplosion";
	global.__objectNames[103] = "Marker";
	global.__objectNames[104] = "FishBoost";
	global.__objectNames[105] = "Ally";
	global.__objectNames[106] = "Infect";
	global.__objectNames[107] = "Partner";
	global.__objectNames[108] = "Sapling";
	global.__objectNames[109] = "AllyFreak";
	global.__objectNames[110] = "CrystalShield";
	global.__objectNames[111] = "GunWarrant";
	global.__objectNames[112] = "EuphoriaShield";
	global.__objectNames[113] = "Rage";
	global.__objectNames[114] = "SheepStorm";
	global.__objectNames[115] = "Notice";
	global.__objectNames[116] = "SleepFX";
	global.__objectNames[117] = "MeltGhost";
	global.__objectNames[118] = "RobotEat";
	global.__objectNames[119] = "SharpTeeth";
	global.__objectNames[120] = "MeltDead";
	global.__objectNames[121] = "Decoy";
	global.__objectNames[122] = "YungCuzDupe";
	global.__objectNames[123] = "ThrowWep";
	global.__objectNames[124] = "AtomPulse";
	global.__objectNames[125] = "Teleport";
	global.__objectNames[126] = "PlantThronebutt";
	global.__objectNames[127] = "UpgradeFX";
	global.__objectNames[128] = "AngelDeflect";
	global.__objectNames[129] = "ArmourStrikeOLD";
	global.__objectNames[130] = "ArmourStrikeHit";
	global.__objectNames[131] = "ArmourStrikeStart";
	global.__objectNames[132] = "ArmourStrike";
	global.__objectNames[133] = "ElementorWallDeflect";
	global.__objectNames[134] = "VikingWall";
	global.__objectNames[135] = "PlayerSpawn";
	global.__objectNames[136] = "RobotTurret";
	global.__objectNames[137] = "AmmoChestMystery";
	global.__objectNames[138] = "HealFX";
	global.__objectNames[139] = "HPPickup";
	global.__objectNames[140] = "AmmoPickup";
	global.__objectNames[141] = "RoguePickup";
	global.__objectNames[142] = "AmmoChest";
	global.__objectNames[143] = "RogueAmmoChest";
	global.__objectNames[144] = "chestprop";
	global.__objectNames[145] = "WeaponChest";
	global.__objectNames[146] = "RadChest";
	global.__objectNames[147] = "HealthChest";
	global.__objectNames[148] = "ChestOpen";
	global.__objectNames[149] = "FXChestOpen";
	global.__objectNames[150] = "BigWeaponChest";
	global.__objectNames[151] = "EliteWeaponChest";
	global.__objectNames[152] = "GiantGoldenWeaponChest";
	global.__objectNames[153] = "Rad";
	global.__objectNames[154] = "WepPickup";
	global.__objectNames[155] = "BigRad";
	global.__objectNames[156] = "GoldChest";
	global.__objectNames[157] = "ProtoChest";
	global.__objectNames[158] = "SlashShotgunPrep";
	global.__objectNames[159] = "SlashDirectorShotgunPrep";
	global.__objectNames[160] = "SlashEraserPrep";
	global.__objectNames[161] = "SlashShotgunBurst";
	global.__objectNames[162] = "SlashDirectorShotgunBurst";
	global.__objectNames[163] = "SlashEraserBurst";
	global.__objectNames[164] = "Burst";
	global.__objectNames[165] = "FrostBurst";
	global.__objectNames[166] = "RogueRifleBurst";
	global.__objectNames[167] = "SwarmBurst";
	global.__objectNames[168] = "RocketGloveBurst";
	global.__objectNames[169] = "SmallGrenadeBurst";
	global.__objectNames[170] = "DoomBurst";
	global.__objectNames[171] = "NukeBurst";
	global.__objectNames[172] = "SeekerShotgunBurst";
	global.__objectNames[173] = "SeekerCannonBurst";
	global.__objectNames[174] = "LaserWaveBurst";
	global.__objectNames[175] = "MissileBurst";
	global.__objectNames[176] = "DirectorBurst";
	global.__objectNames[177] = "SlugBurst";
	global.__objectNames[178] = "ShotgunBurst";
	global.__objectNames[179] = "PistoleBurst";
	global.__objectNames[180] = "BeamShotgunBurst";
	global.__objectNames[181] = "EnergyJackhammerBurst";
	global.__objectNames[182] = "SawBurst";
	global.__objectNames[183] = "FlameBurst";
	global.__objectNames[184] = "SnowBurst";
	global.__objectNames[185] = "SnowDragonBurst";
	global.__objectNames[186] = "TimeThrowerBurst";
	global.__objectNames[187] = "ToxicSound";
	global.__objectNames[188] = "ToxicBurst";
	global.__objectNames[189] = "ToxicDragonBurst";
	global.__objectNames[190] = "ToxicDragonSound";
	global.__objectNames[191] = "DragonBurst";
	global.__objectNames[192] = "DragonSound";
	global.__objectNames[193] = "FlameSound";
	global.__objectNames[194] = "SnowSound";
	global.__objectNames[195] = "SnowDragonSound";
	global.__objectNames[196] = "HeavyBurst";
	global.__objectNames[197] = "BouncerBurst";
	global.__objectNames[198] = "EraserBurst";
	global.__objectNames[199] = "DirectorEraserBurst";
	global.__objectNames[200] = "FlameDirectorEraserBurst";
	global.__objectNames[201] = "EraserBurst2";
	global.__objectNames[202] = "Burst2";
	global.__objectNames[203] = "UltraFlameBurst";
	global.__objectNames[204] = "FlameEraserBurst";
	global.__objectNames[205] = "WaveBurst";
	global.__objectNames[206] = "UltraWaveBurst";
	global.__objectNames[207] = "EnemyWaveBurst";
	global.__objectNames[208] = "EnemyEraserBurst";
	global.__objectNames[209] = "FlameWaveBurst";
	global.__objectNames[210] = "IonBurst";
	global.__objectNames[211] = "KrakenIonBurst";
	global.__objectNames[212] = "ToxicIonBurst";
	global.__objectNames[213] = "SuperIonBurst";
	global.__objectNames[214] = "ChargeShotgun";
	global.__objectNames[215] = "ChargeSplinterGun";
	global.__objectNames[216] = "ChargeFlakCannon";
	global.__objectNames[217] = "ChargeLaser";
	global.__objectNames[218] = "WeaponCharge";
	global.__objectNames[219] = "HumphryProjectile";
	global.__objectNames[220] = "projectile";
	global.__objectNames[221] = "MeatExplosion";
	global.__objectNames[222] = "Shell";
	global.__objectNames[223] = "EnemyBullet1";
	global.__objectNames[224] = "EnemyBullet2";
	global.__objectNames[225] = "LightningHit";
	global.__objectNames[226] = "LightningSpawn";
	global.__objectNames[227] = "Lightning";
	global.__objectNames[228] = "Tentacle";
	global.__objectNames[229] = "UltraLightning";
	global.__objectNames[230] = "LaserCannon";
	global.__objectNames[231] = "BloodBullet";
	global.__objectNames[232] = "MiniFlameCannonBall";
	global.__objectNames[233] = "EnemyLightningBall";
	global.__objectNames[234] = "FlameCannonBall";
	global.__objectNames[235] = "BloodCannonBall";
	global.__objectNames[236] = "ToxicCannonBall";
	global.__objectNames[237] = "IceCannonBall";
	global.__objectNames[238] = "HeavyBullet";
	global.__objectNames[239] = "FatBullet";
	global.__objectNames[240] = "FrozenEnemy";
	global.__objectNames[241] = "FrozenPlayer";
	global.__objectNames[242] = "PartnerBullet";
	global.__objectNames[243] = "FreezeBullet";
	global.__objectNames[244] = "Bullet3";
	global.__objectNames[245] = "EnemyBouncerBullet";
	global.__objectNames[246] = "Morph";
	global.__objectNames[247] = "ExplosiveMorph";
	global.__objectNames[248] = "Ray";
	global.__objectNames[249] = "Implosion";
	global.__objectNames[250] = "Slug";
	global.__objectNames[251] = "UltraSlug";
	global.__objectNames[252] = "DirectorSlug";
	global.__objectNames[253] = "HeavySlug";
	global.__objectNames[254] = "EnemyBullet3";
	global.__objectNames[255] = "BulletHit";
	global.__objectNames[256] = "LaserCharge";
	global.__objectNames[257] = "PlasmaBall";
	global.__objectNames[258] = "ElectroBallSpawn";
	global.__objectNames[259] = "ElectroBall";
	global.__objectNames[260] = "PopoPlasmaBall";
	global.__objectNames[261] = "MiniPlasmaBall";
	global.__objectNames[262] = "PlasmaBig";
	global.__objectNames[263] = "PlasmaHuge";
	global.__objectNames[264] = "BloodGrenade";
	global.__objectNames[265] = "PopoNade";
	global.__objectNames[266] = "Grenade";
	global.__objectNames[267] = "SplitGrenade";
	global.__objectNames[268] = "DoomNadeCluster";
	global.__objectNames[269] = "DoomGrenade";
	global.__objectNames[270] = "Termite";
	global.__objectNames[271] = "SmallGrenade";
	global.__objectNames[272] = "Flare";
	global.__objectNames[273] = "FrostFlare";
	global.__objectNames[274] = "TimeReset";
	global.__objectNames[275] = "TimeBomb";
	global.__objectNames[276] = "Rocket";
	global.__objectNames[277] = "FlakBullet";
	global.__objectNames[278] = "FrostFlakBullet";
	global.__objectNames[279] = "UltraFlakBullet";
	global.__objectNames[280] = "SuperFlakBullet";
	global.__objectNames[281] = "SuperBouncerFlakBullet";
	global.__objectNames[282] = "BouncerFlakBullet";
	global.__objectNames[283] = "AllyBullet";
	global.__objectNames[284] = "IDPDBullet";
	global.__objectNames[285] = "EnemyLaser";
	global.__objectNames[286] = "IDPDLaser";
	global.__objectNames[287] = "EnemyBullet4";
	global.__objectNames[288] = "EnemyBullet5";
	global.__objectNames[289] = "JockRocket";
	global.__objectNames[290] = "PopoMissile";
	global.__objectNames[291] = "HyperGrenade";
	global.__objectNames[292] = "HyperSniper";
	global.__objectNames[293] = "HyperLightning";
	global.__objectNames[294] = "LineGrenade";
	global.__objectNames[295] = "HyperInfuseBolt";
	global.__objectNames[296] = "LineToxic";
	global.__objectNames[297] = "LineBlood";
	global.__objectNames[298] = "LineFire";
	global.__objectNames[299] = "EnemyLineFire";
	global.__objectNames[300] = "HyperPlasmaCannon";
	global.__objectNames[301] = "HyperBloodGrenade";
	global.__objectNames[302] = "HyperSlug";
	global.__objectNames[303] = "HyperHeavySlug";
	global.__objectNames[304] = "PopoSlug";
	global.__objectNames[305] = "Bullet1";
	global.__objectNames[306] = "MoneyBullet";
	global.__objectNames[307] = "RogueBullet";
	global.__objectNames[308] = "DisperseBullet";
	global.__objectNames[309] = "DisperseDisperseBullet";
	global.__objectNames[310] = "DisperseRocket";
	global.__objectNames[311] = "DispersePellet";
	global.__objectNames[312] = "DisperseLaser";
	global.__objectNames[313] = "AIBullet";
	global.__objectNames[314] = "Bullet2";
	global.__objectNames[315] = "Potato";
	global.__objectNames[316] = "Bullet6";
	global.__objectNames[317] = "Bullet4";
	global.__objectNames[318] = "Bullet5";
	global.__objectNames[319] = "Bullet8";
	global.__objectNames[320] = "Bullet7";
	global.__objectNames[321] = "Bullet9";
	global.__objectNames[322] = "Nuke";
	global.__objectNames[323] = "SterNuke";
	global.__objectNames[324] = "Laser";
	global.__objectNames[325] = "MegaLaser";
	global.__objectNames[326] = "Splinter";
	global.__objectNames[327] = "UltraSplinter";
	global.__objectNames[328] = "InfuseBolt";
	global.__objectNames[329] = "UltraInfuseBolt";
	global.__objectNames[330] = "SwordBullet";
	global.__objectNames[331] = "ShankBullet";
	global.__objectNames[332] = "EnergySwordBullet";
	global.__objectNames[333] = "EnergyShankBullet";
	global.__objectNames[334] = "BoltTrail";
	global.__objectNames[335] = "GoldenExplosiveBolt";
	global.__objectNames[336] = "ToxicBolt";
	global.__objectNames[337] = "ExplosiveBolt";
	global.__objectNames[338] = "Bolt";
	global.__objectNames[339] = "LightningBolt";
	global.__objectNames[340] = "HeavyBolt";
	global.__objectNames[341] = "UltraBolt";
	global.__objectNames[342] = "SeekerBolt";
	global.__objectNames[343] = "SwarmBolt";
	global.__objectNames[344] = "Missile";
	global.__objectNames[345] = "EnemyMissile";
	global.__objectNames[346] = "UltraSeekerBolt";
	global.__objectNames[347] = "BoltStick";
	global.__objectNames[348] = "GyroBurst";
	global.__objectNames[349] = "Disc";
	global.__objectNames[350] = "PermanentDisc";
	global.__objectNames[351] = "Blade";
	global.__objectNames[352] = "Yoyo";
	global.__objectNames[353] = "SplitBlade";
	global.__objectNames[354] = "SuperSplitBlade";
	global.__objectNames[355] = "UltraBlade";
	global.__objectNames[356] = "EnemyDisc";
	global.__objectNames[357] = "DiscTrail";
	global.__objectNames[358] = "DiscBounce";
	global.__objectNames[359] = "DiscDisappear";
	global.__objectNames[360] = "Deflect";
	global.__objectNames[361] = "Flame";
	global.__objectNames[362] = "IceFlame";
	global.__objectNames[363] = "UltraFlame";
	global.__objectNames[364] = "PlasmaImpact";
	global.__objectNames[365] = "PopoPlasmaImpact";
	global.__objectNames[366] = "MiniPlasmaImpact";
	global.__objectNames[367] = "PlasmaFX";
	global.__objectNames[368] = "IonImpact";
	global.__objectNames[369] = "EnemySlash";
	global.__objectNames[370] = "AssassinSlash";
	global.__objectNames[371] = "PopoSlash";
	global.__objectNames[372] = "EnergySlash";
	global.__objectNames[373] = "GhettoBlast";
	global.__objectNames[374] = "EnergyHammerSlash";
	global.__objectNames[375] = "EnergyShank";
	global.__objectNames[376] = "Shank";
	global.__objectNames[377] = "LightningShank";
	global.__objectNames[378] = "Slash";
	global.__objectNames[379] = "BlackSwordSlash";
	global.__objectNames[380] = "DarkSwordSlash";
	global.__objectNames[381] = "GhostEffect";
	global.__objectNames[382] = "GhostSlash";
	global.__objectNames[383] = "RocketSlash";
	global.__objectNames[384] = "BigSlash";
	global.__objectNames[385] = "FrostSlash";
	global.__objectNames[386] = "BloodSlash";
	global.__objectNames[387] = "LightningSlash";
	global.__objectNames[388] = "KrakenSlash";
	global.__objectNames[389] = "MorphSlash";
	global.__objectNames[390] = "EBulletHit";
	global.__objectNames[391] = "ExplosionNonLethal";
	global.__objectNames[392] = "Explosion";
	global.__objectNames[393] = "ExplosionMask";
	global.__objectNames[394] = "SmallExplosion";
	global.__objectNames[395] = "ExplosionStop";
	global.__objectNames[396] = "WallBreak";
	global.__objectNames[397] = "PopoExplosion";
	global.__objectNames[398] = "MeleeHitWall";
	global.__objectNames[399] = "ToxicThrowerGas";
	global.__objectNames[400] = "ToxicGas";
	global.__objectNames[401] = "TrapFire";
	global.__objectNames[402] = "Mine";
	global.__objectNames[403] = "SentryGun";
	global.__objectNames[404] = "hitme";
	global.__objectNames[405] = "enemy";
	global.__objectNames[406] = "SpikeTrap";
	global.__objectNames[407] = "MaggotSpawn";
	global.__objectNames[408] = "MaggotExplosion";
	global.__objectNames[409] = "MaggotExplosionInverted";
	global.__objectNames[410] = "Maggot";
	global.__objectNames[411] = "MaggotInverted";
	global.__objectNames[412] = "ChesireCatTail";
	global.__objectNames[413] = "You";
	global.__objectNames[414] = "InvertedChesireCatTail";
	global.__objectNames[415] = "WantBoss";
	global.__objectNames[416] = "ChesireCatExplosion";
	global.__objectNames[417] = "ChesireCat";
	global.__objectNames[418] = "InvertedChesireCat";
	global.__objectNames[419] = "BecomeScrapBoss";
	global.__objectNames[420] = "ScrapBoss";
	global.__objectNames[421] = "InvertedScrapBoss";
	global.__objectNames[422] = "BecomeInvertedScrapBoss";
	global.__objectNames[423] = "ScrapBossMissile";
	global.__objectNames[424] = "BanditBoss";
	global.__objectNames[425] = "InvertedBanditBoss";
	global.__objectNames[426] = "ScrapBossCorpse";
	global.__objectNames[427] = "BigDogExplo";
	global.__objectNames[428] = "HotDrakePrepSmoke";
	global.__objectNames[429] = "HotDrake";
	global.__objectNames[430] = "InvertedHotDrake";
	global.__objectNames[431] = "HotDrakeFlameCannon";
	global.__objectNames[432] = "HotDrakeSplitBall";
	global.__objectNames[433] = "InvertedHotDrakeSplitBall";
	global.__objectNames[434] = "LilHunter";
	global.__objectNames[435] = "LilHunterDie";
	global.__objectNames[436] = "LilHunterFly";
	global.__objectNames[437] = "InvertedLilHunterDie";
	global.__objectNames[438] = "InvertedLilHunterFly";
	global.__objectNames[439] = "InvertedLilHunter";
	global.__objectNames[440] = "BigFish";
	global.__objectNames[441] = "BigMachineTurret";
	global.__objectNames[442] = "BigMachineLaser";
	global.__objectNames[443] = "BigMachineMask";
	global.__objectNames[444] = "BigMachine";
	global.__objectNames[445] = "InvertedBigMachineTurret";
	global.__objectNames[446] = "InvertedBigMachineLaser";
	global.__objectNames[447] = "InvertedBigMachine";
	global.__objectNames[448] = "LabTrap";
	global.__objectNames[449] = "AssassinBoss";
	global.__objectNames[450] = "InvertedAssassinBoss";
	global.__objectNames[451] = "FireBaller";
	global.__objectNames[452] = "SuperFireBaller";
	global.__objectNames[453] = "FireBat";
	global.__objectNames[454] = "LavaBallEnemy";
	global.__objectNames[455] = "InvertedLavaBallEnemy";
	global.__objectNames[456] = "InvertedSuperFireBaller";
	global.__objectNames[457] = "InvertedFireBaller";
	global.__objectNames[458] = "InvertedFireBat";
	global.__objectNames[459] = "Necromancer";
	global.__objectNames[460] = "InvertedNecromancer";
	global.__objectNames[461] = "Freak";
	global.__objectNames[462] = "InvertedFreak";
	global.__objectNames[463] = "ExploFreak";
	global.__objectNames[464] = "InvertedExploFreak";
	global.__objectNames[465] = "ReviveFX";
	global.__objectNames[466] = "ReviveArea";
	global.__objectNames[467] = "InvertedReviveArea";
	global.__objectNames[468] = "RhinoFreak";
	global.__objectNames[469] = "InvertedRhinoFreak";
	global.__objectNames[470] = "MutantTube";
	global.__objectNames[471] = "InvertedMutantTube";
	global.__objectNames[472] = "Bandit";
	global.__objectNames[473] = "LaserBandit";
	global.__objectNames[474] = "JungleBandit";
	global.__objectNames[475] = "EraserBandit";
	global.__objectNames[476] = "BanditInverted";
	global.__objectNames[477] = "CardGuy2";
	global.__objectNames[478] = "CardGuy";
	global.__objectNames[479] = "TeaPot";
	global.__objectNames[480] = "TeaPotMissile";
	global.__objectNames[481] = "InvertedCardGuy";
	global.__objectNames[482] = "InvertedCardGuy2";
	global.__objectNames[483] = "InvertedTeaPot";
	global.__objectNames[484] = "TeaPotNuke";
	global.__objectNames[485] = "becomenemy";
	global.__objectNames[486] = "BigMaggotBurrow";
	global.__objectNames[487] = "BigMaggot";
	global.__objectNames[488] = "BigMaggotBurrowInverted";
	global.__objectNames[489] = "BigMaggotInverted";
	global.__objectNames[490] = "Molesarge";
	global.__objectNames[491] = "Molefish";
	global.__objectNames[492] = "Mimic";
	global.__objectNames[493] = "SuperMimic";
	global.__objectNames[494] = "LaserCrystal";
	global.__objectNames[495] = "LightningCrystal";
	global.__objectNames[496] = "Spider";
	global.__objectNames[497] = "InvertedSpider";
	global.__objectNames[498] = "RadMaggotChest";
	global.__objectNames[499] = "RadMaggotExplosion";
	global.__objectNames[500] = "RadMaggot";
	global.__objectNames[501] = "Gator";
	global.__objectNames[502] = "GatorSmoke";
	global.__objectNames[503] = "InvertedGator";
	global.__objectNames[504] = "Exploder";
	global.__objectNames[505] = "InvertedExploder";
	global.__objectNames[506] = "InvertedSuperFrog";
	global.__objectNames[507] = "ExploderExplo";
	global.__objectNames[508] = "SuperFrog";
	global.__objectNames[509] = "Rat";
	global.__objectNames[510] = "InvertedRat";
	global.__objectNames[511] = "FastRat";
	global.__objectNames[512] = "InvertedFastRat";
	global.__objectNames[513] = "Ratking";
	global.__objectNames[514] = "InvertedRatking";
	global.__objectNames[515] = "RatkingRage";
	global.__objectNames[516] = "InvertedRatkingRage";
	global.__objectNames[517] = "Raven";
	global.__objectNames[518] = "Thief";
	global.__objectNames[519] = "RavenFly";
	global.__objectNames[520] = "Salamander";
	global.__objectNames[521] = "InvertedSalamander";
	global.__objectNames[522] = "Sniper";
	global.__objectNames[523] = "InvertedSniper";
	global.__objectNames[524] = "InvertedRaven";
	global.__objectNames[525] = "InvertedRavenFly";
	global.__objectNames[526] = "MeleeBandit";
	global.__objectNames[527] = "MeleeFake";
	global.__objectNames[528] = "InvertedMeleeFake";
	global.__objectNames[529] = "InvertedMeleeBandit";
	global.__objectNames[530] = "Jock";
	global.__objectNames[531] = "SnowMan";
	global.__objectNames[532] = "GoldScorpion";
	global.__objectNames[533] = "Scorpion";
	global.__objectNames[534] = "InvertedScorpion";
	global.__objectNames[535] = "ScorpionBulletHit";
	global.__objectNames[536] = "BoneFish";
	global.__objectNames[537] = "Crab";
	global.__objectNames[538] = "Turtle";
	global.__objectNames[539] = "Trap";
	global.__objectNames[540] = "TrapScorchMark";
	global.__objectNames[541] = "Wolf";
	global.__objectNames[542] = "SnowBot";
	global.__objectNames[543] = "SnowBotCar";
	global.__objectNames[544] = "DiscGuy";
	global.__objectNames[545] = "GoldSnowTank";
	global.__objectNames[546] = "SnowTank";
	global.__objectNames[547] = "SnowTankExplo";
	global.__objectNames[548] = "InvertedSnowTank";
	global.__objectNames[549] = "InvertedDiscGuy";
	global.__objectNames[550] = "InvertedWolf";
	global.__objectNames[551] = "InvertedSnowBot";
	global.__objectNames[552] = "InvertedSnowBotCar";
	global.__objectNames[553] = "Inspector";
	global.__objectNames[554] = "SegwayPopo";
	global.__objectNames[555] = "Shielder";
	global.__objectNames[556] = "IDPDSpawn";
	global.__objectNames[557] = "IDPDPortalCharge";
	global.__objectNames[558] = "Grunt";
	global.__objectNames[559] = "VanSpawn";
	global.__objectNames[560] = "IDPDVan";
	global.__objectNames[561] = "EliteGrunt";
	global.__objectNames[562] = "EliteShielder";
	global.__objectNames[563] = "EliteInspector";
	global.__objectNames[564] = "PopoShield";
	global.__objectNames[565] = "Sheep";
	global.__objectNames[566] = "ExplosiveSheep";
	global.__objectNames[567] = "AcidStreak";
	global.__objectNames[568] = "AutoAimUpDown";
	global.__objectNames[569] = "BECOMETARGET";
	global.__objectNames[570] = "prop";
	global.__objectNames[571] = "Server";
	global.__objectNames[572] = "InvertedServer";
	global.__objectNames[573] = "Terminal";
	global.__objectNames[574] = "InvertedTerminal";
	global.__objectNames[575] = "Barrel";
	global.__objectNames[576] = "Tube";
	global.__objectNames[577] = "InvertedTube";
	global.__objectNames[578] = "StreetLight";
	global.__objectNames[579] = "Torch";
	global.__objectNames[580] = "Tires";
	global.__objectNames[581] = "ToxicBarrel";
	global.__objectNames[582] = "SodaMachine";
	global.__objectNames[583] = "BigFishSkull";
	global.__objectNames[584] = "Anchor";
	global.__objectNames[585] = "WaterMineExplo";
	global.__objectNames[586] = "WaterMine";
	global.__objectNames[587] = "BigSkull";
	global.__objectNames[588] = "Cactus";
	global.__objectNames[589] = "Coral";
	global.__objectNames[590] = "WaterPlant";
	global.__objectNames[591] = "CandyCane";
	global.__objectNames[592] = "Mushroom";
	global.__objectNames[593] = "BigMushroom";
	global.__objectNames[594] = "BloodStreak";
	global.__objectNames[595] = "Bones";
	global.__objectNames[596] = "TopDecal";
	global.__objectNames[597] = "Breath";
	global.__objectNames[598] = "CanSpawnBoss";
	global.__objectNames[599] = "Car";
	global.__objectNames[600] = "CarThrow";
	global.__objectNames[601] = "CarVenus";
	global.__objectNames[602] = "CarVenusFixed";
	global.__objectNames[603] = "CaveSparkle";
	global.__objectNames[604] = "CharredGround";
	global.__objectNames[605] = "Cocoon";
	global.__objectNames[606] = "Corpse";
	global.__objectNames[607] = "Crown";
	global.__objectNames[608] = "CrownGuardian";
	global.__objectNames[609] = "GuardianStatue";
	global.__objectNames[610] = "GuardianDeflect";
	global.__objectNames[611] = "CrownPed";
	global.__objectNames[612] = "WeaponMod";
	global.__objectNames[613] = "CrownPickup";
	global.__objectNames[614] = "Crystal";
	global.__objectNames[615] = "Curse";
	global.__objectNames[616] = "Debris";
	global.__objectNames[617] = "Drama";
	global.__objectNames[618] = "DramaCamera";
	global.__objectNames[619] = "Drip";
	global.__objectNames[620] = "Dust";
	global.__objectNames[621] = "GoldBarrel";
	global.__objectNames[622] = "Hydrant";
	global.__objectNames[623] = "LavaBubble";
	global.__objectNames[624] = "LevelUp";
	global.__objectNames[625] = "LogMenu";
	global.__objectNames[626] = "MoneyPile";
	global.__objectNames[627] = "Pipe";
	global.__objectNames[628] = "PizzaBox";
	global.__objectNames[629] = "PizzaEntrance";
	global.__objectNames[630] = "PopupText";
	global.__objectNames[631] = "Portal";
	global.__objectNames[632] = "PortalShock";
	global.__objectNames[633] = "ProtoStatue";
	global.__objectNames[634] = "RainDrop";
	global.__objectNames[635] = "RainSplash";
	global.__objectNames[636] = "ImpactFX";
	global.__objectNames[637] = "MeltSplat";
	global.__objectNames[638] = "Scorchmark";
	global.__objectNames[639] = "Flames";
	global.__objectNames[640] = "PopoFlames";
	global.__objectNames[641] = "BigScorchMark";
	global.__objectNames[642] = "SmallChestFade";
	global.__objectNames[643] = "SmallChestPickup";
	global.__objectNames[644] = "Smoke";
	global.__objectNames[645] = "SnowFlake";
	global.__objectNames[646] = "Spiral";
	global.__objectNames[647] = "SpiralCont";
	global.__objectNames[648] = "SpiralDebris";
	global.__objectNames[649] = "SpiralStar";
	global.__objectNames[650] = "TV";
	global.__objectNames[651] = "WepSwap";
	global.__objectNames[652] = "Wind";
	global.__objectNames[653] = "WindNight";
	global.__objectNames[654] = "YVStatue";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
