{
  "bboxMode": 0,
  "collisionKind": 1,
  "type": 0,
  "origin": 9,
  "preMultiplyAlpha": false,
  "edgeFiltering": false,
  "collisionTolerance": 0,
  "swfPrecision": 2.525,
  "bbox_left": 8,
  "bbox_right": 68,
  "bbox_top": 20,
  "bbox_bottom": 89,
  "HTile": false,
  "VTile": false,
  "For3D": false,
  "width": 80,
  "height": 100,
  "textureGroupId": {
    "name": "PlayerCharacter",
    "path": "texturegroups/PlayerCharacter",
  },
  "swatchColours": null,
  "gridX": 0,
  "gridY": 0,
  "frames": [
    {"compositeImage":{"FrameId":{"name":"1be59fda-33df-4d56-a92b-e3e7eb899ecb","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"1be59fda-33df-4d56-a92b-e3e7eb899ecb","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"1be59fda-33df-4d56-a92b-e3e7eb899ecb","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"a2f79f91-18f3-461a-9912-7c4aba8ea08a","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"a2f79f91-18f3-461a-9912-7c4aba8ea08a","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"a2f79f91-18f3-461a-9912-7c4aba8ea08a","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"056da59c-7d56-4072-b2f2-96ab632a0188","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"056da59c-7d56-4072-b2f2-96ab632a0188","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"056da59c-7d56-4072-b2f2-96ab632a0188","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"842eac22-b701-496b-8c59-93c5af3174d4","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"842eac22-b701-496b-8c59-93c5af3174d4","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"842eac22-b701-496b-8c59-93c5af3174d4","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"c5906e08-4528-4e56-aa43-297681a57764","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"c5906e08-4528-4e56-aa43-297681a57764","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"c5906e08-4528-4e56-aa43-297681a57764","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"c0f18769-508b-4bc3-b298-24a8ccfe7c0b","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"c0f18769-508b-4bc3-b298-24a8ccfe7c0b","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"c0f18769-508b-4bc3-b298-24a8ccfe7c0b","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"7cb37eda-60af-48b7-9a41-c837badd99c0","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"7cb37eda-60af-48b7-9a41-c837badd99c0","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"7cb37eda-60af-48b7-9a41-c837badd99c0","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"58d49824-d17f-4d65-87d8-9bcb48dbc919","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"58d49824-d17f-4d65-87d8-9bcb48dbc919","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"58d49824-d17f-4d65-87d8-9bcb48dbc919","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"de5796cd-6810-40d7-8adb-44b2d0632039","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"de5796cd-6810-40d7-8adb-44b2d0632039","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"de5796cd-6810-40d7-8adb-44b2d0632039","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"cf58d171-6037-4299-91f2-bef5efb53770","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"cf58d171-6037-4299-91f2-bef5efb53770","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"cf58d171-6037-4299-91f2-bef5efb53770","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"f255bc14-fc31-42dc-b4dd-161971481dc1","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"f255bc14-fc31-42dc-b4dd-161971481dc1","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"f255bc14-fc31-42dc-b4dd-161971481dc1","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"b44b5e00-fb5a-4000-80c7-f4ffbd7babe5","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"b44b5e00-fb5a-4000-80c7-f4ffbd7babe5","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"b44b5e00-fb5a-4000-80c7-f4ffbd7babe5","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"b3afdd70-7bba-4692-afcb-f31a42b3ba36","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"b3afdd70-7bba-4692-afcb-f31a42b3ba36","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"b3afdd70-7bba-4692-afcb-f31a42b3ba36","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"15b42623-3f99-4376-bbf8-fb4a4de16cc4","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"15b42623-3f99-4376-bbf8-fb4a4de16cc4","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"15b42623-3f99-4376-bbf8-fb4a4de16cc4","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"91d0c78b-c6df-4467-8194-fb08ec229338","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"91d0c78b-c6df-4467-8194-fb08ec229338","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"91d0c78b-c6df-4467-8194-fb08ec229338","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"451655bb-be9c-4a0e-9c07-a0111d42a2d3","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"451655bb-be9c-4a0e-9c07-a0111d42a2d3","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"451655bb-be9c-4a0e-9c07-a0111d42a2d3","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"a0f553ee-d159-48e0-9549-756d74de7eb6","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"a0f553ee-d159-48e0-9549-756d74de7eb6","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"a0f553ee-d159-48e0-9549-756d74de7eb6","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"3eee646b-bdc2-442f-92c9-3c050f6390c5","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"3eee646b-bdc2-442f-92c9-3c050f6390c5","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"3eee646b-bdc2-442f-92c9-3c050f6390c5","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"15969f9e-1b3e-43b7-8cd5-c65788a31aed","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"15969f9e-1b3e-43b7-8cd5-c65788a31aed","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"15969f9e-1b3e-43b7-8cd5-c65788a31aed","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"543a64cb-551c-4806-8e1d-12f21e58e283","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"543a64cb-551c-4806-8e1d-12f21e58e283","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"543a64cb-551c-4806-8e1d-12f21e58e283","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"d8696a39-b8fc-445e-a8bb-b73c1fcba74a","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"d8696a39-b8fc-445e-a8bb-b73c1fcba74a","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"d8696a39-b8fc-445e-a8bb-b73c1fcba74a","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"d5b0e3d9-508a-4ca7-8900-0b5dfced693f","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"d5b0e3d9-508a-4ca7-8900-0b5dfced693f","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"d5b0e3d9-508a-4ca7-8900-0b5dfced693f","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"4bcaa918-bd19-4b2c-a3ac-000f33e5a11d","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"4bcaa918-bd19-4b2c-a3ac-000f33e5a11d","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"4bcaa918-bd19-4b2c-a3ac-000f33e5a11d","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"80b7df85-d262-4857-a9f5-db8a6ad1b8ae","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"80b7df85-d262-4857-a9f5-db8a6ad1b8ae","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"80b7df85-d262-4857-a9f5-db8a6ad1b8ae","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"5faf92c3-7b2f-4f74-909d-09f971b57259","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"5faf92c3-7b2f-4f74-909d-09f971b57259","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"5faf92c3-7b2f-4f74-909d-09f971b57259","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"e67b29ef-d9be-4e14-a297-6f21f4d34da2","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"e67b29ef-d9be-4e14-a297-6f21f4d34da2","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"e67b29ef-d9be-4e14-a297-6f21f4d34da2","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"d661dc90-f157-462d-be8e-eac8d87dff60","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"d661dc90-f157-462d-be8e-eac8d87dff60","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"d661dc90-f157-462d-be8e-eac8d87dff60","tags":[],"resourceType":"GMSpriteFrame",},
    {"compositeImage":{"FrameId":{"name":"e1e267b0-b08f-4f73-a5bf-3fcb09f32f85","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":null,"resourceVersion":"1.0","name":"imported","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"e1e267b0-b08f-4f73-a5bf-3fcb09f32f85","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"LayerId":{"name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","name":"e1e267b0-b08f-4f73-a5bf-3fcb09f32f85","tags":[],"resourceType":"GMSpriteFrame",},
  ],
  "sequence": {
    "spriteId": {"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},
    "timeUnits": 1,
    "playback": 1,
    "playbackSpeed": 1.0,
    "playbackSpeedType": 1,
    "autoRecord": true,
    "volume": 1.0,
    "length": 28.0,
    "events": {"Keyframes":[],"resourceVersion":"1.0","resourceType":"KeyframeStore<MessageEventKeyframe>",},
    "moments": {"Keyframes":[],"resourceVersion":"1.0","resourceType":"KeyframeStore<MomentsEventKeyframe>",},
    "tracks": [
      {"name":"frames","spriteId":null,"keyframes":{"Keyframes":[
            {"id":"52c29466-0d40-4e63-a64f-4f31a36d6086","Key":0.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"1be59fda-33df-4d56-a92b-e3e7eb899ecb","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"3a04379d-deae-481e-b9db-35737adf862a","Key":1.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"a2f79f91-18f3-461a-9912-7c4aba8ea08a","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"ed471fb5-0dcb-43f9-a388-368d214856d8","Key":2.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"056da59c-7d56-4072-b2f2-96ab632a0188","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"f598b114-7f06-42c6-b94b-3630334ca273","Key":3.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"842eac22-b701-496b-8c59-93c5af3174d4","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"e2536898-d569-42f7-b17b-13b52ab43687","Key":4.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"c5906e08-4528-4e56-aa43-297681a57764","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"9a4bc7b4-e60d-400b-b5ad-de5ebfeb7485","Key":5.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"c0f18769-508b-4bc3-b298-24a8ccfe7c0b","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"9a234f8c-15a3-4ad6-83b9-fce8e128766e","Key":6.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"7cb37eda-60af-48b7-9a41-c837badd99c0","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"e5c140f4-2861-4211-aefa-a5f4a9cc85ef","Key":7.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"58d49824-d17f-4d65-87d8-9bcb48dbc919","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"9afbda2c-5837-4ecf-9654-71c94d716c03","Key":8.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"de5796cd-6810-40d7-8adb-44b2d0632039","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"dcd5fa95-463f-4c86-a46d-fc35b112756a","Key":9.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"cf58d171-6037-4299-91f2-bef5efb53770","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"7adb9c54-ed00-4736-87e5-6cd2998f4c2a","Key":10.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"f255bc14-fc31-42dc-b4dd-161971481dc1","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"a209bafc-52db-498c-93bd-8041313b41e0","Key":11.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"b44b5e00-fb5a-4000-80c7-f4ffbd7babe5","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"029d153f-0f01-4974-8a1c-31df71ecaae4","Key":12.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"b3afdd70-7bba-4692-afcb-f31a42b3ba36","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"c544a1be-0cdf-4a5b-add6-c04a4fd75915","Key":13.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"15b42623-3f99-4376-bbf8-fb4a4de16cc4","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"ce1d5362-b069-48d4-b550-88a4cd7e8a2c","Key":14.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"91d0c78b-c6df-4467-8194-fb08ec229338","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"3d973f9b-00ff-42c5-89e3-56aba2de3836","Key":15.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"451655bb-be9c-4a0e-9c07-a0111d42a2d3","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"8b1f0442-bcd7-477e-a87e-0430e9935510","Key":16.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"a0f553ee-d159-48e0-9549-756d74de7eb6","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"d75fbba0-981e-4e48-9177-6db9f1ef601f","Key":17.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"3eee646b-bdc2-442f-92c9-3c050f6390c5","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"de4f8bad-89d4-4bd1-9c41-1831d2c7fce9","Key":18.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"15969f9e-1b3e-43b7-8cd5-c65788a31aed","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"ca1c2e3a-e8e8-4f37-992d-530947e99b10","Key":19.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"543a64cb-551c-4806-8e1d-12f21e58e283","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"0a860c39-4655-4d57-8408-80bcde3089d9","Key":20.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"d8696a39-b8fc-445e-a8bb-b73c1fcba74a","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"a4bfe386-5e5a-4449-8503-5a9699b11510","Key":21.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"d5b0e3d9-508a-4ca7-8900-0b5dfced693f","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"947a3823-15e3-43d5-be96-8c60a499d796","Key":22.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"4bcaa918-bd19-4b2c-a3ac-000f33e5a11d","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"2a4509ae-f918-47aa-8a59-ce3fbd2bac88","Key":23.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"80b7df85-d262-4857-a9f5-db8a6ad1b8ae","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"12ec2ba0-4f76-449d-96e7-424a41d5e8ed","Key":24.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"5faf92c3-7b2f-4f74-909d-09f971b57259","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"27819450-4563-42da-9bc6-44a68d5ec107","Key":25.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"e67b29ef-d9be-4e14-a297-6f21f4d34da2","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"68b8bb2f-6195-42e1-9667-82e2e8ffb477","Key":26.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"d661dc90-f157-462d-be8e-eac8d87dff60","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
            {"id":"ea24923d-5b5d-4f7d-84f7-42575886d304","Key":27.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"e1e267b0-b08f-4f73-a5bf-3fcb09f32f85","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
          ],"resourceVersion":"1.0","resourceType":"KeyframeStore<SpriteFrameKeyframe>",},"trackColour":0,"inheritsTrackColour":true,"builtinName":0,"traits":0,"interpolation":1,"tracks":[],"events":[],"isCreationTrack":false,"resourceVersion":"1.0","tags":[],"resourceType":"GMSpriteFramesTrack","modifiers":[],},
    ],
    "visibleRange": null,
    "lockOrigin": false,
    "showBackdrop": true,
    "showBackdropImage": false,
    "backdropImagePath": "",
    "backdropImageOpacity": 0.5,
    "backdropWidth": 1920,
    "backdropHeight": 1080,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "xorigin": 41,
    "yorigin": 70,
    "eventToFunction": {},
    "eventStubScript": null,
    "parent": {"name":"sprInvertedCubeGuardianFireHurt","path":"sprites/sprInvertedCubeGuardianFireHurt/sprInvertedCubeGuardianFireHurt.yy",},
    "resourceVersion": "1.4",
    "name": "sprInvertedCubeGuardianFireHurt",
    "tags": [],
    "resourceType": "GMSequence",
  },
  "layers": [
    {"visible":true,"isLocked":false,"blendMode":0,"opacity":100.0,"displayName":"default","resourceVersion":"1.0","name":"5269b1c6-2687-4cc8-aa83-d0485794dc3c","tags":[],"resourceType":"GMImageLayer",},
  ],
  "nineSlice": null,
  "parent": {
    "name": "InvertedPalaceEnemies",
    "path": "folders/Sprites/Palace/Palace Enemy/InvertedPalaceEnemies.yy",
  },
  "resourceVersion": "1.0",
  "name": "sprInvertedCubeGuardianFireHurt",
  "tags": [],
  "resourceType": "GMSprite",
}