///scrDecideGameoverText();
// /@description
///@param
function scrDecideGameoverText(){
	var gmt = "YOU DID NOT REACH THE NUCLEAR THRONE";
	if BackCont.loops > 9
		{
			gmt = choose(
			"WORLD RECORD!?","BRUH WHAT WAS THIS SETUP?",
			"PLEASE NERF THIS SETUP","ABSOLUTLY INSANE","WORLD RECORD!","DOUBLE DIGIT LOOP!",
			"YOU ARE INSANE!","THAT WAS A REALLY LONG RUN","BEST THRONER EVER!"
			);	
		}
		if BackCont.loops > 4
		{
			gmt = choose(
			"DID YOU RECORD THAT?","ABSOLUTLY CRACKED AT THE GAME","GAMER",
			"YOU DESTROYED THE NUCLEAR THRONE","YOU LOOPED","AWESOME!","THAT WAS A GOOD RUN","GREAT WORK","AMAZING","ITS A LOOP!","VERY WELL PLAYED",
			"MORE THAN ONE LOOP!?","GREAT NOW DO IT AGAIN!","AMAZING RUN!","CRACKED","ABOVE AND BEYOND","BRUH WHAT WAS THIS SETUP?",
			"PLEASE NERF THIS SETUP","ABSOLUTLY INSANE","WOOOOOO","YOU ARE INSANE!","WOW!"
			);	
		}
		else if BackCont.loops > 2
		{
			gmt = choose(
			"AMAZING","YOU ARE INSANE!","WOW!","WHAT A RUN!",
			"YOU DESTROYED THE NUCLEAR THRONE","YOU LOOPED","AWESOME!","THAT WAS A GOOD RUN","GREAT WORK","AMAZING","ITS A LOOP!","VERY WELL PLAYED",
			"MORE THAN ONE LOOP!?","GREAT NOW DO IT AGAIN!","AMAZING RUN!","CRACKED","ABOVE AND BEYOND","YEA!"
			);	
		}
		else if BackCont.loops > 1
		{
			gmt = choose(
			"GREAT WORK","WELL PLAYED","WELL DONE",
			"YOU DESTROYED THE NUCLEAR THRONE","YOU LOOPED","AWESOME!","THAT WAS A GOOD RUN","GREAT WORK","AMAZING","ITS A LOOP!","VERY WELL PLAYED",
			"MORE THAN ONE LOOP!?","GREAT NOW DO IT AGAIN!","AMAZING RUN!","CRACKED","ABOVE AND BEYOND","YEA!"
			);	
		}
		if BackCont.loops > 0
		{
			gmt = choose(
			"YOU DESTROYED THE NUCLEAR THRONE","YOU LOOPED","AWESOME!","THAT WAS A GOOD RUN","GREAT WORK","AMAZING","ITS A LOOP!",
			"YOU DESTROYED THE NUCLEAR THRONE","YOU DESTROYED THE NUCLEAR THRONE","VERY WELL PLAYED"
			);
		}
		else if (BackCont.area > 4 && BackCont.area != 10)
		{
			gmt = choose(
			"GREAT WORK","NICE TRY","WELL PLAYED","WELL DONE","GREAT WORK",
			"YOU DID NOT REACH THE NUCLEAR THRONE","YOU ARE AWESOME","YOU ARE GREAT",
			"THAT WAS A GOOD RUN","YOU DID NOT REACH THE NUCLEAR THRONE","YOU DID NOT REACH THE NUCLEAR THRONE"
			);
		} else if (BackCont.area == 1)
		{
			gmt = choose(
			"WASTED","NICE TRY","YOU'LL GET THERE","MEDIOCRE","WHAT WAS THAT?",
			"MISTAKES WERE MADE","IT'S OKE","OOPS","TRASH","KILLED BY FIERCE BANDITS",
			"YOU DID NOT REACH THE NUCLEAR THRONE","YOU DID NOT REACH THE NUCLEAR THRONE","YOU DID NOT REACH THE NUCLEAR THRONE"
			);
		}else
		{
			gmt = choose(
				"NICE TRY","YOU DID NOT REACH THE NUCLEAR THRONE","YOU DID NOT REACH THE NUCLEAR THRONE",
				"BETTER LUCK NEXT TIME","YOU DID NOT REACH THE NUCLEAR THRONE","MISSION FAILED","TRY AGAIN"
				);
		}
	return gmt;
}