image_speed=0.4;
ultramod = 0
ultramodName[0] = "[NOTHING]";
ultramodName[1] = "[NOTHING]";
ultramodDescription = "";
alarm[2] = 1;
wave=random(100);
maxUltramod = UberCont.maxUltramod;
swapper = 1;
alarm[3] = 60;
holdExplainTimer = 0;
